# Generated by Django 4.1.2 on 2022-10-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userrant',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userrant',
            name='username',
        ),
    ]
