# Generated by Django 4.1 on 2022-09-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publication_header',
            new_name='Header',
        ),
    ]
